.TRY Basic configure
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: node node1
.INP: delete node1
.INP: node node1 	attributes mem=16G
.INP: node node2 utilization cpu=4
.INP: primitive st stonith:ssh 	params hostlist='node1 node2' 	meta target-role="Started" 	op start requires=nothing timeout=60s 	op monitor interval=60m timeout=60s
.INP: primitive st2 stonith:ssh 	params hostlist='node1 node2'
.INP: property stonith-enabled=true
.INP: _test
.INP: verify
.EXT crm_resource --show-metadata stonith:ssh
.EXT stonithd metadata
.EXT crmd metadata
.EXT pengine metadata
.EXT cib metadata
.INP: show
node node1 \
       attributes mem=16G
node node2 \
       utilization cpu=4
primitive st stonith:ssh \
       params hostlist="node1 node2" \
       meta target-role=Started \
       op start requires=nothing timeout=60s interval=0 \
       op monitor interval=60m timeout=60s
primitive st2 stonith:ssh \
       params hostlist="node1 node2"
property cib-bootstrap-options: \
       stonith-enabled=true
.INP: commit
