.TRY Basic configure
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: node node1
.INP: delete node1
.INP: node node1 	attributes mem=16G
.INP: node node2 utilization cpu=4
.INP: primitive st stonith:ssh 	params hostlist='node1 node2' 	meta target-role="Started" 	op start timeout=60s 	op monitor interval=60m timeout=60s
.INP: primitive st2 stonith:ssh 	params hostlist='node1 node2'
.INP: primitive d1 ocf:pacemaker:Dummy 	operations $id=d1-ops 	op monitor interval=60m 	op monitor interval=120m OCF_CHECK_LEVEL=10
.INP: monitor d1 60s:30s
.INP: primitive d2 ocf:heartbeat:Delay 	params mondelay=60 	op start timeout=60s 	op stop timeout=60s
.INP: monitor d2:Started 60s:30s
.INP: group g1 d1 d2
.INP: primitive d3 ocf:pacemaker:Dummy
.INP: clone c d3 	meta clone-max=1
.INP: primitive d4 ocf:pacemaker:Dummy
.INP: ms m d4
.INP: delete m
.INP: master m d4
.INP: primitive s5 ocf:pacemaker:Stateful 	operations $id-ref=d1-ops
.INP: primitive s6 ocf:pacemaker:Stateful 	operations $id-ref=d1
.INP: ms m5 s5
.INP: ms m6 s6
.INP: primitive d7 Dummy         params fake=1 extra rule score=inf         expression attribute=#uname operation=eq value=node1         params fake=2 extra rule score=inf         expression attribute=#uname operation=eq value=node2       op start interval=0 timeout=60s         extra score=2 op_param=dummy         rule expression attribute=#uname operation=eq value=node1         extra score=1 op_param=smart         extra op_type=meta score=2 start-delay=120m         rule expression attribute=#ra-version operation=gt value=1.0 type=version         extra op_type=meta score=1 start-delay=60m
.INP: location l1 g1 on node1 score=100
.INP: location l2 c 	rule $id=l2-rule1 score=100 expression attribute=#uname operation=eq value=node1
.INP: location l3 m5         rule score=inf boolean-op=and         expression attribute=#uname operation=eq value=node1         expression attribute=pingd operation=gt value=0
.INP: location l4 m5         rule score=-inf boolean-op=or         expression attribute=pingd operation=not_defined         expression attribute=pingd operation=lte value=0
.INP: location l5 m5         rule score=-inf boolean-op=or         expression attribute=pingd operation=not_defined         expression attribute=pingd operation=lte value=0         rule score=0 boolean-op=and         expression attribute=#uname operation=eq value=node1         expression attribute=pingd operation=gt value=0
.INP: location l6 m5 	rule $id-ref=l2-rule1
.INP: location l7 m5 	rule $id-ref=l2
.INP: colocation c1 m6 with m5 options score=inf
.INP: colocation c2 m5 role=Master with d1 with_role=Started options score=inf
.INP: order o1 first m5 then m6 options kind=Mandatory
.INP: order o2 first d1 first-action=start then m5 then-action=promote options kind=Optional
.INP: order o3 first m5 then m6 options kind=Serialize
.INP: order o4 first m5 then m6
.INP: rsc_ticket ticket-A_m6 ticket-A: m6
.INP: rsc_ticket ticket-B_m6_m5 ticket-B: m6 m5 loss-policy=fence
.INP: rsc_ticket ticket-C_master ticket-C: m6 m5:Master loss-policy=fence
.INP: fencing_topology st st2
.INP: property stonith-enabled=true
.INP: property $id=cpset2 maintenance-mode=true
.INP: rsc_defaults failure-timeout=10m
.INP: op_defaults $id=opsdef2 record-pending=true         rule score=100 expression attribute=#uname operation=eq value=node1
.INP: tag t1: m5 m6
.INP: set d2.mondelay 45
.INP: _test
.INP: verify
.EXT crm_resource --show-metadata stonith:ssh
.EXT stonithd metadata
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Delay
.EXT crm_resource --show-metadata ocf:pacemaker:Stateful
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.EXT crmd metadata
.EXT pengine metadata
.EXT cib metadata
.INP: show
node node1 \
	attributes mem=16G
node node2 \
	utilization cpu=4
primitive d1 ocf:pacemaker:Dummy \
	operations $id=d1-ops \
	op monitor interval=60m \
	op monitor interval=120m \
	    extra OCF_CHECK_LEVEL=10 \
	op monitor interval=60s timeout=30s
primitive d2 Delay \
	params mondelay=45 \
	op start timeout=60s interval=0 \
	op stop timeout=60s interval=0 \
	op monitor role=Started interval=60s timeout=30s
primitive d3 ocf:pacemaker:Dummy
primitive d4 ocf:pacemaker:Dummy
primitive d7 Dummy \
	params fake=1  \
	    extra  \
	    rule score=inf expression attribute="#uname" operation=eq value=node1 \
	params fake=2  \
	    extra  \
	    rule score=inf expression attribute="#uname" operation=eq value=node2 \
	op start interval=0 timeout=60s \
	    extra score=2 op_param=dummy  \
            rule score=inf expression attribute="#uname" operation=eq value=node1 \
	    extra score=1 op_param=smart  \
	    extra score=2 start-delay=120m op_type=meta \
            rule score=inf expression attribute="#ra-version" operation=gt value=1.0 type=version \
            extra score=1 start-delay=60m op_type=meta
primitive s5 ocf:pacemaker:Stateful \
	operations  $id-ref=d1-ops
primitive s6 ocf:pacemaker:Stateful \
	operations  $id-ref=d1-ops
primitive st stonith:ssh \
	params hostlist="node1 node2" \
	meta target-role=Started \
	op start timeout=60s interval=0 \
	op monitor interval=60m timeout=60s
primitive st2 stonith:ssh \
	params hostlist="node1 node2"
group g1 d1 d2
ms m d4
ms m5 s5
ms m6 s6
clone c d3 \
	meta clone-max=1
tag t1 m5 m6
colocation c1 m6 with m5 \
	options score=inf
colocation c2 m5 role=Master with d1 with_role=Started \
	options score=inf
location l1 g1 on node1 score=100
location l2 c \
        rule id=l2-rule1 score=100 expression attribute="#uname" operation=eq value=node1
location l3 m5 \
	rule boolean-op=and score=inf \
	expression attribute="#uname" operation=eq value=node1 \
	expression attribute=pingd operation=gt value=0
location l4 m5 \
        rule boolean-op=or score=-inf \
	expression attribute=pingd operation=not_defined \
	expression attribute=pingd operation=lte value=0
location l5 m5 \
        rule boolean-op=or score=-inf \
	expression attribute=pingd operation=not_defined \
	expression attribute=pingd operation=lte value=0 \
	rule boolean-op=and score=0 \
	expression attribute="#uname" operation=eq value=node1 \
	expression attribute=pingd operation=gt value=0
location l6 m5 \
	rule $id-ref=l2-rule1
location l7 m5 \
	rule $id-ref=l2-rule1
order o1 first m5 then m6 \
	options kind=Mandatory
order o2 first d1 first-action=start then m5 then-action=promote \
	options kind=Optional
order o3 first m5 then m6 \
	options kind=Serialize
order o4 first m5 then m6
fencing_topology st st2
rsc_ticket ticket-A_m6 ticket-A: m6
rsc_ticket ticket-B_m6_m5 ticket-B: m6 m5 loss-policy=fence
rsc_ticket ticket-C_master ticket-C: m6 m5:Master loss-policy=fence
property cib-bootstrap-options: \
	stonith-enabled=true
property cpset2: \
	maintenance-mode=true
rsc_defaults rsc-options: \
	failure-timeout=10m
op_defaults opsdef2: \
	record-pending=true \
	rule score=100 expression attribute="#uname" operation=eq value=node1
.INP: commit
