.TRY Configuration editing
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: op_defaults timeout=2m
.INP: node node1 	attributes mem=16G
.INP: primitive st stonith:null 	params hostlist='node1' 	meta description="some description here" requires=nothing 	op monitor interval=60m
.INP: primitive p1 ocf:heartbeat:Dummy 	op monitor interval=60m 	op monitor interval=120m OCF_CHECK_LEVEL=10
.INP: _test
.INP: verify
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: show
node node1 \
	attributes mem=16G
primitive p1 Dummy \
	op monitor interval=60m \
	op monitor interval=120m \
	    extra OCF_CHECK_LEVEL=10
primitive st stonith:null \
	params hostlist=node1  \
	meta description="some description here" requires=nothing  \
	op monitor interval=60m
op_defaults op-options: \
	timeout=2m
.INP: commit
