.TRY Resource sets
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: node node1
.INP: primitive st stonith:ssh 	params hostlist='node1' 	op start timeout=60s
.INP: primitive d1 ocf:pacemaker:Dummy
.INP: primitive d2 ocf:heartbeat:Dummy
.INP: primitive d3 ocf:heartbeat:Dummy
.INP: primitive d4 ocf:heartbeat:Dummy
.INP: primitive d5 ocf:heartbeat:Dummy
.INP: order o1 resource_set d1 d2 resource_set d3 d4 sequential=false options kind=Serialize
.INP: colocation c1 resource_set d4 resource_set d1 d2 d3 sequential=false options score=inf
.INP: colocation c2 resource_set d1 d2 d3 d4 options score=inf
.INP: colocation c3 resource_set d3 d4 sequential=false resource_set d1 d2 sequential=false options score=inf
.INP: delete d2
INFO: 16: constraint order:o1 updated
INFO: 16: constraint colocation:c1 updated
INFO: 16: constraint colocation:c2 updated
INFO: 16: constraint colocation:c3 updated
.INP: show o1 c1 c2 c3
colocation c1 \
	resource_set d4 \
	resource_set d1 d3 sequential=false \
	options score=inf
colocation c2 \
	resource_set d1 d3 d4 \
	options score=inf
colocation c3 \
	resource_set d3 d4 sequential=false \
	resource_set d1 sequential=false \
	options score=inf
order o1 \
	resource_set d1 \
	resource_set d3 d4 sequential=false \
	options kind=Serialize
.INP: delete d4
INFO: 18: constraint order:o1 updated
INFO: 18: constraint colocation:c1 updated
INFO: 18: constraint colocation:c2 updated
INFO: 18: constraint colocation:c3 updated
.INP: show o1 c1 c2 c3
colocation c1 \
	resource_set d1 d3 sequential=false \
	options score=inf
colocation c2 \
	resource_set d1 d3 \
	options score=inf
colocation c3 \
	resource_set d3 \
	resource_set d1 \
	options score=inf
order o1 \
	resource_set d1 \
	resource_set d3 \
	options kind=Serialize
.INP: _test
.INP: verify
.EXT crm_resource --show-metadata stonith:ssh
.EXT stonithd metadata
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy
primitive d3 Dummy
primitive d5 Dummy
primitive st stonith:ssh \
	params hostlist=node1 \
	op start timeout=60s interval=0
colocation c1 \
	resource_set d1 d3 sequential=false \
	options score=inf
colocation c2 \
	resource_set d1 d3 \
	options score=inf
colocation c3 \
	resource_set d3 \
	resource_set d1 \
	options score=inf
order o1 \
	resource_set d1 \
	resource_set d3 \
	options kind=Serialize
.INP: commit
