<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1"/>
    </nodes>
    <resources>
      <primitive id="st" class="stonith" type="ssh">
        <instance_attributes id="st-instance_attributes">
          <nvpair name="hostlist" value="node1" id="st-instance_attributes-hostlist"/>
        </instance_attributes>
        <operations>
          <op name="start" timeout="60s" interval="0" id="st-start-0"/>
        </operations>
      </primitive>
      <primitive id="d1" class="ocf" provider="pacemaker" type="Dummy"/>
      <primitive id="d3" class="ocf" provider="heartbeat" type="Dummy"/>
      <primitive id="d5" class="ocf" provider="heartbeat" type="Dummy"/>
    </resources>
    <constraints>
      <rsc_order id="o1" kind="Serialize">
        <resource_set id="o1-0">
          <resource_ref id="d1"/>
        </resource_set>
        <resource_set id="o1-1">
          <resource_ref id="d3"/>
        </resource_set>
      </rsc_order>
      <rsc_colocation id="c1" score="INFINITY">
        <resource_set sequential="false" id="c1-1">
          <resource_ref id="d1"/>
          <resource_ref id="d3"/>
        </resource_set>
      </rsc_colocation>
      <rsc_colocation id="c2" score="INFINITY">
        <resource_set id="c2-0">
          <resource_ref id="d1"/>
          <resource_ref id="d3"/>
        </resource_set>
      </rsc_colocation>
      <rsc_colocation id="c3" score="INFINITY">
        <resource_set id="c3-0">
          <resource_ref id="d3"/>
        </resource_set>
        <resource_set id="c3-1">
          <resource_ref id="d1"/>
        </resource_set>
      </rsc_colocation>
    </constraints>
  </configuration>
</cib>
